### PR TITLE
removed error-causing FriendlyPathDeleter line

### PR DESCRIPTION
**Pull request by mpanighetti**
- removed additional FriendlyPathDeleter line which was causing error `unexpected element at line 27` #106
- removed json download and JSONFileReader run in favor of URLTextSearcher ([smaddock's suggestion](https://github.com/autopkg/moofit-recipes/issues/106#issuecomment-1542660441))
- updated FileFinder regex pattern to account for current folder structure
- linted xml

### CODE REVIEW

**Comment by mpanighetti** [comment]
Confirmed successful download with test run:

```
% autopkg run ~/Desktop/ClickShare.download.recipe -v
Processing ~/Desktop/ClickShare.download.recipe...
WARNING: ~/Desktop/ClickShare.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
com.github.smithjw.processors/FriendlyPathDeleter
FriendlyPathDeleter: Path does not exist, skipping: ~/Library/AutoPkg/Cache/com.github.moofit-recipes.download.ClickShare/downloads/ClickShare.zip
URLTextSearcher
URLTextSearcher: Found matching text (match): https://barcoprdwebsitefs.azureedge.net/barcoprdfs/Data/secure/downloads/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_46_ApplicationSw.zip?LDR2GRhnzD2uMXvl9Xzbo4gcJXaZhAmZgSzvsoKQjGv51cOr4Nz1wzrgVLE-suUcVlfno2wcIVkm8EQqLOyvq6KyMXy-","isSuccess":true,"isNotFound":false,"isUnauthorized
URLDownloader
URLDownloader: Storing new Last-Modified header: Wed, 26 Apr 2023 04:00:51 GMT
URLDownloader: Storing new ETag header: "0x8DB460AD3382C6D"
URLDownloader: Downloaded ~/Library/AutoPkg/Cache/com.github.moofit-recipes.download.ClickShare/downloads/ClickShare.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename ClickShare.zip
Unarchiver: Unarchived ~/Library/AutoPkg/Cache/com.github.moofit-recipes.download.ClickShare/downloads/ClickShare.zip to ~/Library/AutoPkg/Cache/com.github.moofit-recipes.download.ClickShare/unpack
FileFinder
FileFinder: Found file match: '~/Library/AutoPkg/Cache/com.github.moofit-recipes.download.ClickShare/unpack/ClickShare_Setup.dmg' from globbed '~/Library/AutoPkg/Cache/com.github.moofit-recipes.download.ClickShare/unpack/*.dmg'
FileFinder: Basename match: 'ClickShare_Setup.dmg'
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image ~/Library/AutoPkg/Cache/com.github.moofit-recipes.download.ClickShare/unpack/ClickShare_Setup.dmg
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /private/tmp/dmg.au5c8W/ClickShare.app: valid on disk
CodeSignatureVerifier: /private/tmp/dmg.au5c8W/ClickShare.app: satisfies its Designated Requirement
CodeSignatureVerifier: /private/tmp/dmg.au5c8W/ClickShare.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Receipt written to ~/Library/AutoPkg/Cache/com.github.moofit-recipes.download.ClickShare/receipts/ClickShare.download-receipt-20230510-225808.plist

The following new items were downloaded:
    Download Path                                                                                                 
    -------------                                                                                                 
    ~/Library/AutoPkg/Cache/com.github.moofit-recipes.download.ClickShare/downloads/ClickShare.zip  
```

**Comment by homebysix** [comment]
@wegotoeleven Could you consider merging this soon? Syntax errors will be visible for anybody with the moofit-recipes repo added in their AutoPkg setup until the path_list array is fixed.

**Comment by homebysix** [comment]
I'm making an executive decision and merging this in. Plist syntax errors cause issues for the whole community and need rapid response when pointed out.

**Comment by dczward** [comment]
I'm still getting an error when trying to run the Clickshare.pkg recipe. If this issue is closed/patched, how do I get that to run?

**Pull request merged**
